codecov:
  notify:
    require_ci_to_pass: yes
coverage:
  ignore:
    - Tests/CustomKeyboardTextField/*.swift
  precision: 2
  round: down
  range: 70...100
  status:
    project: true
    patch: true
    changes: true
comment:
    layout: "header, diff, changes, uncovered"
    behavior: default
